'use strict';

module.exports = {
  CREATE_CAR: 'CREATE_CAR',
  GET_ALL_CARS: 'GET_ALL_CARS',
  EDIT_CAR: 'EDIT_CAR',
  DELETE_CAR: 'DELETE_CAR',
  USER_LOGGED_IN: 'USER_LOGGED_IN',
  USER_LOGGED_OUT: 'USER_LOGGED_OUT',
  USER_REGISTERED: 'USER_REGISTERED'
};